### ISSUE TITLE
Make the search bar responsive

### ISSUE THREAD

**Issue by ribaishtiaq** [ribaishtiaq/Chablie#6]
Make the search bar in navigation bar responsive on mobile and tablet.

Code for search bar can be found here: https://github.com/ribaishtiaq/Chablie/blob/master/app/views/layouts/_header.html.erb

And the SCSS is here: https://github.com/ribaishtiaq/Chablie/blob/master/app/assets/stylesheets/search.scss

**Comment by alexmalus** [comment]
I'll work on this.

**Comment by ribaishtiaq** [comment]
Thanks @alexmalus

**Comment by alexmalus** [comment]
@ribaishtiaq This project is making heavy use of https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css

Can you please share more details about it?

**Comment by ribaishtiaq** [comment]
hi @alexmalus , thats bulma its a css framework, I tried to use that instead of bootstrap because i was having bootstrap errors in productiion but its not working that good, so i will remove it when i'm gonna find a better framework. here the bulma documentation https://bulma.io/documentation/
