### ISSUE TITLE
Make the signup/login form responsive

### ISSUE THREAD

**Issue by ribaishtiaq** [ribaishtiaq/Chablie#7]
Make the signup/login form responsive on mobile and tablet.
the live page: https://chablie.herokuapp.com

Form code can be found here: https://github.com/ribaishtiaq/Chablie/blob/master/app/views/pages/home.html.erb

And scss is here: https://github.com/ribaishtiaq/Chablie/blob/master/app/assets/stylesheets/pages.scss

**Comment by ballin98** [comment]
Hi, can I work on this ?

**Comment by ribaishtiaq** [comment]
hi @ballin98 , sure :)
