### ISSUE TITLE
Make sidenav on messages page closable

### ISSUE THREAD

**Issue by ribaishtiaq** [ribaishtiaq/Chablie#8]
Make the side navigation on messages page closable and make the messages page responsive.
![](https://res.cloudinary.com/areeba/image/upload/v1570274623/scrnli_10_5_2019_4-22-30_PM.png)

Code for messages page can be found here: https://github.com/ribaishtiaq/Chablie/tree/master/app/views/chats

and scss can be found here: https://github.com/ribaishtiaq/Chablie/blob/master/app/assets/stylesheets/custom.scss

**Comment by cinthyaflores** [comment]
Can I work on this?

**Comment by ribaishtiaq** [comment]
hi @cinthyaflores , yeah sure

**Comment by Leonardojrr** [comment]
What version of ruby are you using ?

**Comment by ribaishtiaq** [comment]
hi @Leonardojrr , I'm using  2.6.3
